### PR TITLE
Fix cameraprojection crash - Merge and conflict fix of `bevy/main`

### PR DESCRIPTION
**Pull request by Zoomulator**
# Objective

Merged and fixed conflicts to be up-to-date with `bevy/main`

## Notable conflicts
- `CameraProjectionPlugin<T>` got new trait bounds `T: CameraProjection + Component + GetTypeRegistration`, which conflicted with a doc comment above it.
- `CameraUpdateSystem` struct definition was moved to the line below `CameraProjectionPlugin`
- `check_visibility` is now generic `check_visibility::<WithMesh>` (`view/visibility/mod.rs`)

### CODE REVIEW

**Comment by GitGhillie** [comment]
Something went wrong here if you look at the diff, making it basically impossible for doonv to review this PR.
I think if you fork from doonv again and merge main into it instead rebasing, everything should be ok hopefully

**Comment by Zoomulator** [comment]
> Something went wrong here if you look at the diff, making it basically impossible for doonv to review this PR. I think if you fork from doonv again and merge main into it instead rebasing, everything should be ok hopefully

Yeah, rebasing someone else's PR wasn't the best move. Done a simple merge with the fixed conflicts now.

**Comment by doonv** [comment]
Yeah I think I'll try rebasing it myself.

**Comment by doonv** [comment]
I don't think rebasing is the right thing to do, I'll just do a regular merge.

**Pull request closed without merging**
